### ISSUE TITLE
Label not appearing

### ISSUE THREAD

**Issue by MisutaaAsriel** [aliceisjustplaying/labeler-starter-kit-bsky#3]
I tried setting this up to see how easy it is to test and how hard it would be to run, but even though everything appears to be running without error, the custom label doesn't show up. At all. I've tried different mixes of label properties but it's not showing up; am I doing something wrong?

Console prints `Successfully labeled did:plc:### with labelname` when I like the post from another account, but nothing happens. The label is not applied.

**Comment by nulfrost** [comment]
Running into this issue as well, I'm fairly certain I did all of the steps correctly. My theory is it might be able the reverse proxy part but I'm pretty sure I've set that up correctly too

**Comment by MisutaaAsriel** [comment]
> Running into this issue as well, I'm fairly certain I did all of the steps correctly. My theory is it might be able the reverse proxy part but I'm pretty sure I've set that up correctly too

In my case I wasn't even using a reverse proxy. I was using a DDNS to dynamically set a temporary URL to my IP and port forwarding my router. (Reverse proxy instructions were too confusing to use a URL.)

So I doubt this. I'm thinking APIs changed breaking support, or something else is broken or maybe undocumented. If it is the reverse proxy for you it would suggest something is undocumented by this project.

**Comment by imigueldiaz** [comment]
I don´t know if it's related but in my case I had to adjust main.ts asa I propose on #4 for the listener to listen on all interfaces.

**Comment by KiyoshiYoRHa** [comment]
> I don´t know if it's related but in my case I had to adjust main.ts asa I propose on #4 for the listener to listen on all interfaces.

I'm still new to all of this but I have tried using your suggestion. I did have to alter it to make it go through but it still seems to behaving the same as OP for me as well. Here is my alteration from your suggestion on main.ts:

`labelerServer.app.listen({ port: PORT, host: "0.0.0.0" }, (error, address) => {
          if (error) console.error(error);
            else console.log(`Labeler server listening on ${address}`);
});`

It's still listening to like replies and "successfully labeling" but I still don't see it on my profile. I am using a VPS provided by OVHcloud.

**Comment by brettmillerb** [comment]
Anyone able to spell out where I need to make these changes?

I have the same issue but when I add the labelerServer I get a constructor error

![image](https://github.com/user-attachments/assets/47c08ae9-bc51-45f0-b8b3-442196844faf)

**Comment by MisutaaAsriel** [comment]
Even with the changes I still have no labels showing from the labeler after application.

**Comment by imigueldiaz** [comment]
> Anyone able to spell out where I need to make these changes?
> 
> I replaced
> 
> ```ts
> // labelerServer.start(PORT, (error, address) => {
> //   if (error) {
> //     logger.error('Error starting server: %s', error);
> //   } else {
> //     logger.info(`Labeler server listening on ${address}`);
> //   }
> // });
> 
> labelerServer.app.listen({ port: PORT, host: "0.0.0.0" }, (error, address) => {
>   if (error) console.error(error);
>     else console.log(`Labeler server listening on ${address}`);
> });
> ```
> 
> Logs show the labels are being added and removed but nothing on my profile still 🤔

Is the Labeler server listening on ${address} log been shown? I suppose you have run `bunx @skyware/labeler setup` and put the correct public https address... It shows you smothing if you browse to `<public_https_address>/xrpc/com.atproto.label.queryLabels` ?

**Comment by imigueldiaz** [comment]
> Even with the changes I still have no labels showing from the labeler after application. I'm not using Caddy, but a dynamic DNS (during testing, at least) to configure and test locally.

Is the Labeler server listening on ${address} log been shown? I suppose you have run `bunx @skyware/labeler setup` and put the correct public https address... It shows you smothing if you browse to `<public_https_address>/xrpc/com.atproto.label.queryLabels` ?

**Comment by MisutaaAsriel** [comment]
> Is the Labeler server listening on ${address} log been shown? I suppose you have run `bunx @skyware/labeler setup` and put the correct public https address... It shows you smothing if you browse to `<public_https_address>/xrpc/com.atproto.label.queryLabels` ?

Actually, attempting to query via HTTPS returned an error `The server certificate is invalid: Write EPROTO 5148738136:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:`

I can query via HTTP though fine.

**Comment by MisutaaAsriel** [comment]
Ok so I still need a reverse proxy, DDNS was not enough.

I found easier instructions to follow with caddy and was able to successfully get it working.

The lack of log or console output is annoying though.

**Comment by MisutaaAsriel** [comment]
Ok so I still need a reverse proxy, DDNS was not enough.

I found easier instructions to follow with caddy and was able to successfully get it working.

The lack of log or console output is annoying though.

Consider this resolved

**Comment by brettmillerb** [comment]
> > Anyone able to spell out where I need to make these changes?
> > I replaced
> > ```ts
> > // labelerServer.start(PORT, (error, address) => {
> > //   if (error) {
> > //     logger.error('Error starting server: %s', error);
> > //   } else {
> > //     logger.info(`Labeler server listening on ${address}`);
> > //   }
> > // });
> > 
> > labelerServer.app.listen({ port: PORT, host: "0.0.0.0" }, (error, address) => {
> >   if (error) console.error(error);
> >     else console.log(`Labeler server listening on ${address}`);
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Logs show the labels are being added and removed but nothing on my profile still 🤔
> 
> Is the Labeler server listening on ${address} log been shown? I suppose you have run `bunx @skyware/labeler setup` and put the correct public https address... It shows you smothing if you browse to `<public_https_address>/xrpc/com.atproto.label.queryLabels` ?

I don't see the `console.log` to say the labeler is listening with `bun run start` however.

My fork:
https://github.com/brettmillerb/ao3-bsky-labeler

I think I had it working at one point where it showed on my profile but wasn't showing on my posts
![image](https://github.com/user-attachments/assets/dd9cc7d2-4ff6-4fc6-8194-b5eeb36626fa)

Apologies for the naive questions, I've never used Typescript before but getting there.

**/etc/caddy/Caddyfile**
```
epl.millerb.co.uk {
	reverse_proxy localhost:4100

	# Or serve a PHP site through php-fpm:
	# php_fastcgi localhost:9000
}
```

**Comment by brettmillerb** [comment]
> > @imigueldiaz an pointers on what I'm missing? I think it's something obvious.
> > One thing, which may or may not be valid. When I attempted to run the project as-is I received the following error: ![image](https://private-user-images.githubusercontent.com/24279339/388076322-bb5ac970-d88d-46df-89e2-138061c804c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDYzMjksIm5iZiI6MTczMjEwNjAyOSwicGF0aCI6Ii8yNDI3OTMzOS8zODgwNzYzMjItYmI1YWM5NzAtZDg4ZC00NmRmLTg5ZTItMTM4MDYxYzgwNGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEyMzM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZWM3N2MyNGFiOGU5MWNlNzhjMGQ3YTIyZDZlM2I1N2IzMDI4NDhjYmFjYWIwODE2NTJjMjZmZDUzMjdkMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oXdDqzIWBLuTCoPvQdQ9mZ6clVVBlBZnJtXNBS9vCwE)
> > So I added the import and property as recommended by the error but I can't see that change on any of the other forks of this repo.
> 
> I believe that on my multiples tries it was due to a wrong node version inferior to the recommended one (I'm not a developer of this project, only of my fork of the template)

Hmmm yeah I'm on v18.....good shout! 🤦‍♂️

**Comment by brettmillerb** [comment]
Okay so I rebuilt my VM from scratch, installed all the deps as required and node 21.

Went through the labeler setup again too which now appears to work, receives the post likes and labels the account according to the app

![image](https://github.com/user-attachments/assets/a5b20fba-19ef-440d-a587-f06a316ca7fe)

Labels are showing at the URI now too:
https://epl.millerb.co.uk/xrpc/com.atproto.label.queryLabels

Label doesn't appear on my account though when subscribed and liking the post.
![image](https://github.com/user-attachments/assets/c8cd2977-a009-41bd-b299-241421b89b70)
